name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install Functions
        working-directory: functions
        run: npm ci
      - name: Lint
        working-directory: functions
        run: npx eslint . || true
      - name: Test
        working-directory: functions
        run: npm test || echo "no tests"
      - name: Firebase Deploy (preview)
        if: github.event_name == 'pull_request'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          channelId: 'pr-${{ github.event.pull_request.number }}'
      - name: Firebase Deploy (main)
        if: github.ref == 'refs/heads/main'
        run: |
          npm i -g firebase-tools
          firebase deploy --only functions,hosting --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN